name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: 'stable'
      - name: Install Dependencies
        working-directory: .
        run: flutter pub get
      - name: Build
        working-directory: .
        run: flutter build web --release
      - name: Deploy
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /GTP_v2/
