name: Flutter Web Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: 'stable'
      
      - name: Build
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release --base-href "/GTP_v2/"
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
